/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  // sidebar: [
  //   {
  //     type: 'category',
  //     label: 'Contracts',
  //     items: [
  //       'contracts/overview',
  //       'contracts/guides/l1-contracts',
  //       'contracts/guides/l2-contracts',
  //       'contracts/reference/l1-contracts',
  //       'contracts/reference/l2-contracts',
  //     ]
  //   },
  //   {
  //     type: 'category',
  //     label: 'SDK',
  //     items: [
  //       'sdk/overview',

  //     ]
  //   },
  //   {
  //     type: 'category',
  //     label: 'UX',
  //     items: ['ux/overview']
  //   },
  // ],
   
};

export default sidebars;
